# Generated by Django 2.2.4 on 2020-12-17 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_favorite_books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='uploaded_by',
            new_name='uploaded_by_id',
        ),
    ]
