# Generated by Django 2.2.4 on 2020-12-17 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_favorite_books', '0002_auto_20201217_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='uploaded_by_id',
            new_name='uploaded_by',
        ),
    ]
